name: Trigger auto sync
on:
  workflow_dispatch:
  push:
    branch:
      - master
      - TES-1829

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger TestOps auto sync
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/katalon-studio-samples/testops-sync-script-repo-action/actions/workflows/staging.yml/dispatches \
          -d '{"ref":"main"}'

          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/katalon-studio-samples/testops-sync-script-repo-action/actions/workflows/qa.yml/dispatches \
          -d '{"ref":"main"}'

          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/katalon-studio-samples/testops-sync-script-repo-action/actions/workflows/production.yml/dispatches \
          -d '{"ref":"main"}'
      - uses: actions/checkout@v3
