name: Trigger auto sync
on:
  workflow_dispatch:
  push:
    branch:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Scan repository for QA
        uses: katalon-studio-samples/testops-sync-script-repo-action@main
        with: 
          testops-base-url: https://testops.qa.katalon.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          token: ${{ secrets.TOKEN }}

      - name: Scan repository for staging
        uses: katalon-studio-samples/testops-sync-script-repo-action@main
        with: 
          testops-base-url: https://testops.staging.katalon.com
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          token: ${{ secrets.TOKEN }}
